### ISSUE TITLE
studychap02

### ISSUE THREAD

**Issue by 1027luke** [1027luke/thisisjava#1]
studychap02

**Comment by 1027luke** [comment]
learning about variable

**Comment by maxpaper86** [comment]
**I. Binary,  Otca-decimal, Decimal, Hexadecimal**
1) write decimal value from 0 to 33 for given decimal types
ex.
![image](https://user-images.githubusercontent.com/14872577/58067906-db67e800-7b54-11e9-956a-6d9233290882.png)

**II. type, byte, and bit**
1) int, 4-byte, 32-bit
binary : 0000 0000 0000 0000 0000 0000 0000 0000
decimal: 0

binary:  0000 0000 0000 0000 0000 0001 0010 0110
decimal: 294

2) short, 2-byte, 16-bit

binary:  0000 0000 0000 0110
decimal: 6

3) char, 1-byte, 8-bit
binary:  0000 0010
decimal: 2 

homework -> how does negative value be represent as binary?

**III. type cast (big to small)**

binary : 0010 0110
decimal:  32+4+2 = 38         

int x = 294;
char y = x;
System.out.println(y); -> 38

homework: int -> short
homework: short -> char

**IV. type cast (small to big)**
char y = 38;
int x = y;
System.out.println(x);  -> 38

homework: char -> short
homework: short -> int





1-byte
decimal: 3
binary:   0000 0000

**Comment by maxpaper86** [comment]
java 에서는 char가 1바이트가 아니고 byte를 1바이트로 사용하네..
위에 글에서 char -> byte로 바꿔 생각하면 될듯

**Comment by maxpaper86** [comment]
Two's complement (2의 보수)
양의 binary 값을 음수로, 혹은 음의 binary 값을 양수로 바꾸는 방법

1. 주어진 bit를 모두 반전한다
2. +1을 한다.
