### ISSUE TITLE
[Homework] Operation, Operand, Expression

### ISSUE THREAD

**Issue by maxpaper86** [1027luke/thisisjava#5]
# Operation
- Arithmetic: +, -, *, /, %
- Bit: |, &, ^, ~, >>, <<
- Logical: ==, !=, <, >, <=, >=, ||, &&

# difference between bit and logical expression
- bit: operation takes effect on every single digit of the given data
- logical: given data gets converted to boolean first and only one single digit is used during the operation

# Practice

Consider we are handling one byte data only.

1. Arithmetic expression
```
1. (5*3)%7
```

2. Bit expression
```
1.  5 << 2
2.  7 << 4
3.  112 >> 3
4.  63 >> 5

5.  17 | 5
6.  1 | 50
7.  12 & 11
8.  121 & 12

9.  42 ^ 11
10  7  ^ 37
11. ~43
12. ~110
```

3. Logical expression
```
1. 999 && 0
2. 1 && 1
3. 0 && 0
4. 1 && 999

5. 999 || 0
6. 1 || 1
7. 0 || 0
8. 1 || 999

9. 20 < 20
10. 20 <= 20
11. 40 != 41
12. 11 == 11
```

4. Mixed expression
```
1. print x value for every line
x = 0;
x++;
x += 5;
x <<= 2;
x |= 3;
x = ~x + 1;
x ^= 11;
x = x && 1
```

**Comment by 1027luke** [comment]
1. Arithmetic expression
```
1. 1
```
2. Bit expression
```
1. 20
2. 112
3. 14
4. 3
5. 1
6.  51 
7. 1
8. 1
9. 0
10. 34
11. 0
12. 111
```

3.  Logical expression

```
1.  False
2.  True
3. False
4. True
5.  True
6. True
7. False
8. True
9. False
10. True
11. True
12. True
```

4. Mixed expression
```
0
1
6
24
27
-27
-18
True
```
