### ISSUE TITLE
[Homework] Describe 3 major features of OOP (Object oriented programming)

### ISSUE THREAD

**Issue by maxpaper86** [1027luke/thisisjava#8]
You can either google it or watch youtube to understand what does it mean.

1. Encapsulation
2. Inheritance
3. Polymorphism

**Comment by 1027luke** [comment]
1. A process that can limit a class (to the current methods of their class)
2. A process where one class can use other class' methods and fields
3. A concept which enables users to perform single action in different ways? (https://www.javatpoint.com/runtime-polymorphism-in-java)
